### ISSUE TITLE
Sidebar buttons

### ISSUE THREAD

**Issue by Glitchy-Tozier** [flide/8VIM#121]
1. We already have great shortcuts for selecting text, copying, pasting, for cutting, etc… I'm not sure whether we actually need that `CTRL`-button. Could someone explain why it still exists?
I feel like it just wastes space (and kind of violates that one-handedness-paradigma).
2. Sometimes `CTRL C` randomly doesn't work. No idea why.

**Comment by flide** [comment]
I think a better discussion would be : Which 5 buttons should be visible on the sidebar as of now.

Emoji, and selection keyboard switcher are there to stay. Setting is also good to have.
what would you guys like instead of tab and ctrl?

**Comment by Glitchy-Tozier** [comment]
>Emoji, and selection keyboard switcher are there to stay. Setting is also good to have.

I agree, although the necessity of the settings-button is debatable.
Two thoughts:
1. Having only FOUR buttons sounds better, now that #115 is done. (because the keyboard is less high now)
2. To answer your question: As you know, I currently really like the idea of being able to input special characters easier.
(i'll continue this later)
