### ISSUE TITLE
Cursor out of text input

### ISSUE THREAD

**Issue by BruceMustache** [flide/8VIM#125]
Bug: moving cursor gets it out of text input

**Comment by Glitchy-Tozier** [comment]
What does that mean?

**Comment by BruceMustache** [comment]
For example, open

**Comment by Glitchy-Tozier** [comment]
I think I understand. To me personally, this sounds fun though and i wouldn't mind keeping it.
But let's see what other people think.

**Comment by m-rey** [comment]
I like the functionality a lot, as it allows using the keyboard for even more things.
Rather than removing the behaviour, this functionality should be documented in the readme. See #109
