### ISSUE TITLE
German Layout

### ISSUE THREAD

**Issue by flide** [flide/8VIM#90]
If someone can prepare what a 4 sector German layout should look like, I can implement it quickly.

**Comment by WuerfelDev** [comment]
here's the german 8pen layout 

![Screenshot_20201109-162045__01](https://user-images.githubusercontent.com/12686819/98560196-cd0d0f00-22a7-11eb-93a4-d349714bbda8.png)

**Comment by WuerfelDev** [comment]
and in lowercase it shows a question mark instead of the underscore, an exclamation mark instead of the colon and a @ instead of the #

**Comment by flide** [comment]
Thanks, I can put this in.

**Comment by flide** [comment]
Where are the diacritic letters?

**Comment by WuerfelDev** [comment]
I'm not sure if that's a good layout, it has Y in the first circle...
Also there should be a pop-up for the special characters but it didnt seem to work for me

**Comment by flide** [comment]
back to square one...

**Comment by qoheniac** [comment]
[Here](https://www.sttmedia.com/characterfrequency-german) is a letter frequency table for German and Y was found to be the second least used letter. On the other hand one can see that ß and the umlauts Ä, Ö and Ü are all more common than J, X, Y and Q and therefore should be treated like regular letters.

**Comment by f1reflyyyylmao** [comment]
I asked the people from the neo-layout project for help, but I'm not sure if anyone is willing to help here yet. Those guys have thought about german layouts for a good ten years and are well qualified for the task in my opinion. 

Also @flide You might want to change the title of the issue to "german" :)

**Comment by Glitchy-Tozier** [comment]
Ok, so a few random things I've found on the internet:

The most common bigrams supposedly are **ER** and **EN**. The most common trigrams are **SCH** and **DER**.
(https://de.wikipedia.org/wiki/Deutsches_Alphabet#H%C3%A4ufigkeit_der_Buchstaben_im_Deutschen)
Here you have two graphs that show the frequencies of bi- and trigrams:
Bigrams: https://de.wikipedia.org/w/index.php?title=Datei:Alphabet_bigramm.svg&filetimestamp=20111001100509&
Trigrams:https://de.wikipedia.org/w/index.php?title=Datei:Alphabet_trigramm.svg&filetimestamp=20200529130309&
(I'm honestly not quite sure why the bigram-graph also contains single letters and why the trigram-graph contains bigraphs though...)



> [Here](https://www.sttmedia.com/characterfrequency-german) is a letter frequency table for German and Y was found to be the second least used letter.

He's right, the 8Pen layout is really badly designed to write German text.

>On the other hand one can see that ß and the umlauts Ä, Ö and Ü are all more common than J, X, Y and Q and therefore should be treated like regular letters.

That's a good point, maybe we should go into this direction:
- Either we use some EASY movement to add diacritics to a, o and u.
- Or we use ä,ö and ü as regular characters and create special movements to add the less common letters.
What could these Movements be though? (for some ideas on movement-availability, see #65)

**Comment by m-rey** [comment]
Please also don't forget about `ß`, which is also used more often than `X`.

**Comment by Glitchy-Tozier** [comment]
Correct

**Comment by Glitchy-Tozier** [comment]
I really have the feeling that we first should settle #65, as it's the basis for what options we even have available to us.
Once that's done, then we could look into layouts.

Btw, here's another great resource for n-grams. It says slightly different things than the Wikipedia-Links, but it's pretty well ordered (except for the monograms) and even contains quadgrams:
http://practicalcryptography.com/cryptanalysis/letter-frequencies-various-languages/german-letter-frequencies/ is a really

**Comment by flide** [comment]
@Glitchy-Tozier , the link you provided has all the necessary details i guess to move this forward. Thanks


So German has 30 characters, and the four sector board fits 32. 

which two(doubled to 4 with shift) extra characters would you want on the board? 

for example, currently we have the following extras : 
?
' 
. 
, 
@ 
! 
* 
"
- 
_ 
@gmail.com 
!

**Comment by Glitchy-Tozier** [comment]
@flide What are you going to do with the remaining ones?

Personally, i think `. , ! ?` are mandatory.
But i kind of also need `*.` And `"`. And `_`...

**Comment by weinland** [comment]
I would love to have a German layout, too.

In my opinion we should go for . , ? @ - on the main dial. Since ß does not necessarily need an uppercase letter we should be fine with that. Or how about a fifth circle for additional characters? Just an idea.

**Comment by Glitchy-Tozier** [comment]
@weinland You might want to check out #65, read through the ideas and post your opinion.  :)

@flide Is it the same layout as the english one or did you move around letters?
If you did the latter, what did you do exactly? Pictures?

**Comment by flide** [comment]
Game plan : 

In the issue #99, @sslater11 showed a basic script to measure frequency of characters, bigrams and trigrams. But I believe the dataset used is very small. 

I am going to repeat the experiment with a much larger dataset, using one or more from the following link 
https://lionbridge.ai/datasets/20-best-german-language-datasets-for-machine-learning/

I am going to post the results and try to create a board manually.

**Comment by Glitchy-Tozier** [comment]
@flide I appreciate the effort. However, I'm not sure, whether you need to put in all that work because
1. There are tons of sites where you can find letter frequencies (and bigram-frequencies) for German (and other languages). Here are three sources:
http://practicalcryptography.com/cryptanalysis/letter-frequencies-various-languages/german-letter-frequencies/
http://www.mathe.tu-freiberg.de/~hebisch/cafe/kryptographie/bigramme.html
https://de.wikipedia.org/w/index.php?title=Datei:Alphabet_bigramm.svg&filetimestamp=20111001100509&
Here's a collection of the most common bigrams:
```
ER :  3.90        ST :  1.21        SE :  0.83
EN :  3.61        NE :  1.19        IT :  0.81
CH :  2.36        BE :  1.17        DI :  0.81
DE :  2.31        ES :  1.17        IC :  0.80
EI :  1.98        UN :  1.13        SC :  0.77
TE :  1.98        RE :  1.11        LE :  0.73
IN :  1.71        AN :  1.07        DA :  0.72
ND :  1.68        HE :  0.89        NS :  0.71
IE :  1.48        AU :  0.89        IS :  0.70
GE :  1.45        NG :  0.87        RA :  0.69
```
(This can be found here: http://practicalcryptography.com/cryptanalysis/letter-frequencies-various-languages/german-letter-frequencies/ . You can click on "german_bigrams.txt" to get an ENORMOUS List of bigrams)

2. I kind of already did that  xD
Yesterday and today, I sat down for (too) many hours and thought about what layout we could use. (assuming, that we find a way to insert `ä`, `ö`, `ü`, and `ß` here: https://github.com/flide/8VIM/issues/65#issuecomment-732735251)
And I created a layout that has the most frequent letters in the inner layers, has good flow and is as smooth as possible for all the common Bi-grams. (not just the ones in that small table. I used the german_bigrams.txt (http://practicalcryptography.com/media/cryptanalysis/files/german_bigrams.txt) so I could even think about less common ones.

**Comment by Glitchy-Tozier** [comment]
Here's what it looks like:
![Vim-German-Layout](https://user-images.githubusercontent.com/59611881/100076360-6c520a80-2e41-11eb-859c-51fc6d3d9463.jpeg)

**Comment by flide** [comment]
why are there no german diacritic letters on the board you created?

**Comment by Glitchy-Tozier** [comment]
Thanks for the quick reply!

As I said, because I think we need a way to input Diacritics separately. (#65)
Also, I dislike the thought of removing symbols. There are few to begin with, but we need `.`, `,`, `?`, `!`, `"`, `*`, `-`, `_`, etc. And they need to be easily accessible.

**Comment by Glitchy-Tozier** [comment]
Regarding the German layout: It might not seem that structured at first, but try those things:
1. Compare it to tables of the most common letters. All the layers are correct. (I moved y in one layer and put x in the outermost layer. This doesn't influence German writing at all, but it gives us compatibility with English. (Y is way more common in English `you`)
2. Check the bigram-list I've posted before and see how well it flows. Obviously, not all Letter-combinations will work (`TE` is the worst contender of the common bigrams), but it's not possible to have everything flow into everything. We need to optimize for the most common combinations. And this layout is really good at that.
Notice how nice most of those bigrams flow.
3. Language compatibility. I made sure, to make the keyboard-layout compatible with English. (Actually, I think it might be better than the current English layout for writing English text. But let's not get into that)
I made sure, that
- Letter Frequency of the English language wasn't ignored (I swapped the layers of `y` <-> `x`)
- **English bigrams also were considered** when creating this layout.
I made sure that bigrams like `th`, `he`, `in`, and `ed` flowed well and were easy to input, even though they wouldn't have mattered _that much_ in German.
Here's a good page for English bigrams I mainly used: http://practicalcryptography.com/cryptanalysis/letter-frequencies-various-languages/english-letter-frequencies/

**Comment by flide** [comment]
I am a little doubtful... if the more frequent letters of the language are not accessible then it defeats the purpose on language specific board. 
I also understand the significance of symbols that you are worried about. 

Give me some time, I will try and focus on layout after the next release.

Obviously, your thoughts are welcome and are my only widow to understanding the boards for other languages.

**Comment by Glitchy-Tozier** [comment]
> if the more frequent letters of the language are not accessible

Could you specify what letters you're talking about?
If it's the `y` and `x` thing, this is a really small change. they are in the top 3 least common letters of German, so swapping two of them is a change that doesn't impact anything. I only factored in English letters and bigrams where the Positioning didn't matter for German. (= German obviously was the main priority) And it worked out pretty well.


> Give me some time, I will try and focus on layout after the next release.

Sure take your time! Looking forward to finally settling this and #65!

**Comment by flide** [comment]
I like the 'wrap up' the word concept. I will keep that in mind.

**Comment by Glitchy-Tozier** [comment]
@flide once that script from #99 is finished and you have the data from LONG German texts (preferably include some random novels / fantasy e-books), I'll be happy to test my Layout again and see whether i need to change something.

**Comment by Glitchy-Tozier** [comment]
> I asked the people from the neo-layout project for help, but I'm not sure if anyone is willing to help here yet. Those guys have thought about german layouts for a good ten years and are well qualified for the task in my opinion.

Because of you I looked into and now started learning the KOY keyboard layout!!
