### ISSUE TITLE
Danish layout

### ISSUE THREAD

**Issue by eyJhb** [flide/8VIM#96]
There is a need for æ ø and å for a danish layout.
I am not sure of the best way to place this. Maybe there could be a combo to translate aa to å, oe to ø and se to æ?

Here is a frequency of chars for danish layout - https://www.sttmedia.com/characterfrequency-danish

**Comment by WuerfelDev** [comment]
For reference the danish layout from 8pen from 2011

![Screenshot_20201114-233328__01](https://user-images.githubusercontent.com/12686819/99158358-2cb55100-26d2-11eb-8605-143b81fb6ca2.png)

![Screenshot_20201114-233403__01](https://user-images.githubusercontent.com/12686819/99158359-2d4de780-26d2-11eb-8035-3ab3680000ab.png)

**Comment by Glitchy-Tozier** [comment]
Sounds like #65 should be settled fist, as `æ`, `ø`, and `å` maybe could be inserted the way diacritics would.

**Comment by Glitchy-Tozier** [comment]
You might be interested in this:
https://github.com/flide/8VIM/discussions/138
