### ISSUE TITLE
My thoughts for a more efficient layout

### ISSUE THREAD

**Issue by sslater11** [flide/8VIM#99]
I was wondering how the layout was originally designed, and if it could be more efficient.

So a quick google of the most frequent letter in English gives us letters in this order
etaoinsrhldcumfpgwybvkxjqz

Most of the letters on the left are the easiest to enter on vim8, but they aren't exactly the same.

I also wondered how that list of letters was generated, and so I generated my own list.
I found this site with the most common 2267 words, and how frequent they are.
https://www.talkenglish.com/vocabulary/top-2000-vocabulary.aspx

I then added each word to a list and I added the word as many times as it's frequency. So the word "the" has a frequency of 9243, so it was added to my list 9243 times.
I then scanned through that list of words and counted every time a letter was found.

I also added a comma and full stop, and made up it's frequency by finding out the average sentence length. Google says it's about 14-20 and the word list was made from 250000 words, so divide that by 15 and we get 16,666.

Here's the output of my script I wrote.
```
Section - letter - frequency - percent
1       - e      - 60053     - 11.5%
1       - t      - 50397     - 9.65%
1       - o      - 44538     - 8.53%
1       - a      - 43136     - 8.26%
1       - n      - 32383     - 6.2%
1       - i      - 32161     - 6.16%
1       - r      - 29350     - 5.62%
1       - h      - 29205     - 5.59%
2       - s      - 24025     - 4.6%
2       - l      - 18595     - 3.56%
2       - .      - 16666     - 3.19%
2       - ,      - 16666     - 3.19%
2       - d      - 15183     - 2.91%
2       - u      - 15085     - 2.89%
2       - f      - 14202     - 2.72%
2       - c      - 13093     - 2.51%
3       - m      - 12306     - 2.36%
3       - y      - 12001     - 2.3%
3       - w      - 9957      - 1.91%
3       - p      - 8772      - 1.68%
3       - b      - 7487      - 1.43%
3       - g      - 6823      - 1.31%
3       - v      - 4871      - 0.93%
3       - k      - 3323      - 0.64%
4       - x      - 977       - 0.19%
4       - j      - 535       - 0.1%
4       - q      - 360       - 0.07%
4       - z      - 185       - 0.04%
```

As you can see, the comma and full stop are only 2 sections away, which surprised me and makes me sceptical of my own results lol.

I'm curious as to other's thoughts on this and whether it's even necessary to try to optimise this layout. I've only just started learning vim8's normal layout, so I haven't gained a decent speed with it yet.

**Comment by flide** [comment]
oh my god!! 

brilliant bit of research. awesome!

**Comment by m-rey** [comment]
Nice research! Thanks for your time and effort!

This basically calculates the char frequency of the most common English words instead of all the English words. I like the idea of restricting the frecuency to only the most common words. However, I'm unsure if the discrepancies between your results and the ones more commonly found on the internet come from the restriction you set or simply because different sources/texts are being used here. Nevertheless, great job! 
 
We have keep in mind that this only takes into account single characters. In my opinion, it would be also helpful to also take a look at the frequency of bi- and trigrams, as you'll normally want a combination of letters to be easy to "type"/"swipe"/"loop". The character combination frequencies can quite differ from the single character frecuencies. I think this has also been mentioned in another issue. 

Furthermore, if I remember correctly, the original 8pen paper states that for their layout, they didn't just try to minimize the average length of a loop, but also tried to quantify and factor in how easy it is to keep the "flow" of consecutive loops.
Meaning that while on average, words could be written using shorter loops using a different layout, they opted to use a layout that on average maybe has slightly longer loops to spell words, if that layout also improves the flow of writing.

In the end, I think that there's a fundamental trade-off between flow and shortness of loops. The current layout is something in-between that is both comfortable to use and efficient, when writing in English.

**Comment by sslater11** [comment]
So I took into account of what you said and modified my script to account for letter pairs and to count their occurrences.
as you can see th and he occur a lot, because the word "the" has those in it and it shows up a lot in English.

Below is the result, which I cut off after 0.5%, because well it was a long list.
```
letters - frequency - percent
th      - 18570     - 5.09%
he      - 14368     - 3.94%
an      - 10076     - 2.76%
re      - 7935      - 2.17%
in      - 7847      - 2.15%
er      - 6963      - 1.91%
nd      - 6846      - 1.88%
or      - 6490      - 1.78%
to      - 6282      - 1.72%
ou      - 6264      - 1.72%
of      - 5733      - 1.57%
at      - 5713      - 1.57%
on      - 5209      - 1.43%
is      - 4960      - 1.36%
ar      - 4927      - 1.35%
ha      - 4667      - 1.28%
it      - 4455      - 1.22%
en      - 4341      - 1.19%
al      - 4235      - 1.16%
st      - 3769      - 1.03%
ve      - 3723      - 1.02%
se      - 3460      - 0.95%
te      - 3322      - 0.91%
yo      - 3262      - 0.89%
me      - 3243      - 0.89%
nt      - 3179      - 0.87%
as      - 3178      - 0.87%
ti      - 2942      - 0.81%
ea      - 2858      - 0.78%
hi      - 2769      - 0.76%
le      - 2763      - 0.76%
be      - 2752      - 0.75%
ur      - 2626      - 0.72%
fo      - 2619      - 0.72%
om      - 2559      - 0.7%
ll      - 2496      - 0.68%
ma      - 2424      - 0.66%
ro      - 2338      - 0.64%
ca      - 2312      - 0.63%
ho      - 2304      - 0.63%
wh      - 2297      - 0.63%
ic      - 2287      - 0.63%
ne      - 2287      - 0.63%
us      - 2264      - 0.62%
es      - 2241      - 0.61%
so      - 2168      - 0.59%
co      - 2151      - 0.59%
ch      - 2019      - 0.55%
ce      - 2016      - 0.55%
ng      - 2013      - 0.55%
ut      - 2009      - 0.55%
wi      - 2008      - 0.55%
il      - 1953      - 0.54%
ly      - 1907      - 0.52%
si      - 1896      - 0.52%
no      - 1846      - 0.51%
de      - 1819      - 0.5%
```

**Comment by koalp** [comment]
@sslater11 nice research !
May I ask for a link to the script ? I'm was planning to try to do the same for french.
*My dream is to have an algorithm to automate the generation of a layout for several languages 😅*

**Comment by sslater11** [comment]
@koalp here it is :). https://github.com/sslater11/vim8_keyboard_most_common_letters
As you can see, it was only a quick python script. Notice the most common letters one has the alphabet put in a python array, because it was a really quick and easy way to do it. If you needed the code to be more dynamic and detect letters and add them to the list once it finds them(easier than remembering what accented letters are in each language), just say and it'll be easy to do.

Haha I did make a keyboard layout generator in Java for the standard android keyboard layouts, but I clearly messed up the maths, or make my rules way too strict, because it took forever to swap keys around and eventually it got stuck in an endless loop as it thought it found the best layout. My idea there was to keep common letters away from each other, so we don't accidentally type in/on, out/put, if/of. My biggest annoyance with keyboards is accidentally pressing the wrong key that is way too close to another. But yeah, I'd love an automatic keyboard generator that could make typing more efficient. I'm liking what vim8 has to offer though, so gonna stick with it and see what happens.

**Comment by WuerfelDev** [comment]
8pen was based on such a combination too: https://github.com/michaelfester/mastodon#unigrams

**Comment by Glitchy-Tozier** [comment]
Ok, a few random ideas/points I'd like to make:

1. Just in case you haven't seen it, here's a blog post from 8pen on how they decided their layout.
[8penresearch.pdf](https://github.com/flide/8VIM/files/5591140/8penresearch.pdf)

2. A thing i thought was SUPER WEIRD is that they didn't even create the layout according to their own rules. Placing `y` in the innermost circle is a weird choice considering it should actually be in the **third** layer.

3. I think, we shouldn't use that "focus on word-endings"-approach (from the pdf). We should make the keyboard as comfortable to write with as possible ... and not just optimize it for the word-endings.
Bigrams is what we should look at. (and of course letter-frequencies to determine the layers)

4. Here's a good page for English bigrams: http://practicalcryptography.com/cryptanalysis/letter-frequencies-various-languages/english-letter-frequencies/ (click on the "english_bigrams.txt")

5. When analyzing letter&bigram frequencies, we should be careful not to use a faulty word source.
**First**, analyzing a dictionary corpus is ... dangerous. Completely different letters can be common. (https://en.wikipedia.org/wiki/Letter_frequency look at the graph.) We should stick to "normal" texts.
**Second**, i think we should not just analyze the most common words. Just analyze a big text. Just go find some random e-books available for free. If certain letters (or bigrams) are common, they will show themselves. No need to risk distorting our letter/bigram-frequency-results by only using some handpicked words.

6. Regarding `.` and `,`, I'll just copy my thoughts from my post from https://github.com/flide/8VIM/issues/90#issuecomment-732790012:
>"_But why didn't you move `.` and `,` up into inner layers??  They are more common than stuff like `Q`!!_"
I thought about that. But this is why I didn't move them further inwards:
In natural writing, at the end of a word you pause briefly. Currently this is achieved by needing to re-tap the circle/center section. And the choice of putting `.` and `,` and all the other special characters in the outermost layer has the same intention. Completing this nice, round gesture
1. Feels like a good way to "wrap up" a word.
2. Gives you more time to prepare yourself mentally for the next word.

**Comment by Kamul-PL** [comment]
I'm wondering if it's a good idea to change the layout of this keyboard. The problem is, that some users are used to to the current layout. So, maybe a small speed increase isn't worth of learning the new layout? Besides that, we are talking about more efficient layout for English language. That doesn't mean it would be more efficient for other languages.

**Comment by sslater11** [comment]
Hey everyone, so I thought I'd give making the layout a go, and this is what I came up with.

So comparing my script's frequent letter output to the one at http://practicalcryptography.com/media/cryptanalysis/files/english_monograms.txt the results are almost the same, except for 4 letters

```
 Section  | My script | Their script | 8vim default
Section 1 |     h     |      s       |      s
Section 2 |     s     |      h       |      h

Section 1 |           |              |      y
Section 2 |     y     |      g       |
Section 3 |     g     |      y       |      g
```

There's really not much difference between what I came up with and what they came up with, so I'll just go with my script's output as it means I'm still working from the same train of thought.

I've decided to keep the fullstop and comma where they are on the original pen8 layout, because I really think we should have another way of entering symbols altogether as they're different from spelling.

I started with the pen8 layout and swapped the relevant letters around so it's in order with my script's output.
![vim8-swapped-keys](https://user-images.githubusercontent.com/43177940/100164445-c7bae180-2eaf-11eb-8c3a-b2b86e789357.jpg)

Then I sat down and went through all the bigrams I posted and tried to swap letters around to improve the feeling of flow.
I like how it's come out, and there's only a few bigrams that it doesn't 'flow' with, although some of the most common ones are within the first section, so they're still quick to swipe at least.

I added up the frequency percent of the bigrams that have a nice flow and it works out about 60% of the most frequent bigrams in English have a nice flow with this layout. It's probably higher since I stopped testing after going through about 70%. Please note that what I mean by these percentages is not "I got 60% through the list", instead "I added 'th' with 5.09% and 'he' with 3.94% to get 9.03%"

![vim8-my-layout-v2](https://user-images.githubusercontent.com/43177940/100164477-d6a19400-2eaf-11eb-9800-022809664a26.jpg)

```
My layout
Here's the ones I found don't really flow on my layout.
letters - frequency - percent
or      - 6490      - 1.78%
at      - 5713      - 1.57%
en      - 4341      - 1.19%
st      - 3769      - 1.03%
ea      - 2858      - 0.78%
hi      - 2769      - 0.76%
ro      - 2338      - 0.64%
ne      - 2287      - 0.63%
il      - 1953      - 0.54%
si      - 1896      - 0.52%
io      - 1805      - 0.49%
mo      - 1780      - 0.49%
li      - 1646      - 0.45%
ta      - 1577      - 0.43%
rt      - 1272      - 0.35%
ct      - 1216      - 0.33%
```


**Comparison** 
I thought I'd go through my list of bigrams using the 8pen layout and I found that my layout has more bigrams that flow and it also has a slightly higher percentage of frequent bigrams that flow too.

The total frequency percent is 73.55% of all the bigrams I went through.
Adding up all the ones that flow
My layout gets 61.57%
The pen8 gets 54.67
A total difference of 6.9%.

So really my layout has only a slight increase in flow, although I did notice a few extra bigrams that didn't feel too smooth in the 8pen layout.

Mine didn't flow with 16/81 bigrams.
Theirs didn't flow with 27/81 bigrams.

```
8pen layout
Here's the ones that didn't really flow on their layout.
letters - frequency - percent
or      - 6490      - 1.78%
of      - 5733      - 1.57%
on      - 5209      - 1.43%
ha      - 4667      - 1.28%
st      - 3769      - 1.03%
as      - 3178      - 0.87%
be      - 2752      - 0.75%
om      - 2559      - 0.7 %
ro      - 2338      - 0.64%
ca      - 2312      - 0.63%
ne      - 2287      - 0.63%
us      - 2264      - 0.62%
ut      - 2009      - 0.55%
il      - 1953      - 0.54%
ly      - 1907      - 0.52%
si      - 1896      - 0.52%
no      - 1846      - 0.51%
de      - 1819      - 0.5% 
io      - 1805      - 0.49%
et      - 1740      - 0.48%
ec      - 1725      - 0.47%
li      - 1646      - 0.45%
ri      - 1537      - 0.42%
fi      - 1436      - 0.39%
ge      - 1400      - 0.38%
we      - 1369      - 0.38%
rt      - 1272      - 0.35%
```

**Comment by Glitchy-Tozier** [comment]
Two somewhat random things I would like to say:

1. @sslater Could you maybe modify your software to also calculate the combined frequency of bigrams IN ANY ORDER?
What i mean by this is: You have the frequency of `ed`. You have the frequency of `de`. Add them together and make a new list of the most common of these combinations.
```
ed+de = 3,34%
en+ne = 3,70%
.
.
.
```
Why would this be useful? **To decide what letters should be opposite each other so they can be easily typed in any order.** For example, if we find out that `de + ed` is the most common bigram-pair, we should place `d` and `e` opposite each other, because this move needs to be fluid in both directions.

2.  #110

Also, regarding this:
> I've decided to keep the fullstop and comma where they are on the original pen8 layout, because I really think we should have another way of entering symbols altogether as they're different from spelling.

That would be amazing! I find it pretty annoying to write things like this: `"Hello"` or `firstword-secondword` as some important special symbols (`_`, `-`, `"`, and `*`) are locked away behind the uppercase-modifier. `*` probably is the worst one because it may be used quite often by people writing markup-like texts. This is a problem in Github and Whatsapp for example.

**Comment by Glitchy-Tozier** [comment]
Does my first request make sense? I'm not sure whether i explained it properly.

**Comment by sslater11** [comment]
@Glitchy-Tozier Yes it does, I will work on it in a bit. If I've not done it in a day or two, just post asking on my progress to remind me :).

**Comment by Glitchy-Tozier** [comment]
Ok, great!

**Comment by Glitchy-Tozier** [comment]
>I've decided to keep the fullstop and comma where they are on the original pen8 layout, because I really think we should have another way of entering symbols altogether as they're different from spelling

I just realized one thing: if you're redesigning the (English) keyboard, i agree to keep `question mark` and `exlamation mark` and all the other "ending-symbols" on the outside layers. Because of this:

>"But why didn't you move . and , up into inner layers?? They are more common than stuff like Q!!"
I thought about that. But this is why I didn't move them further inwards:
In natural writing, at the end of a word you pause briefly. Currently this is achieved by needing to re-tap the circle/center section. And the choice of putting . and , and all the other special characters in the outermost layer has the same intention. Completing this nice, round gesture
- Feels like a good way to "wrap up" a word.
- Gives you more time to prepare yourself mentally for the next word.

However, something like this `'` should very much be treated like a regular letter. It doesn't occur at the end of words and it isn't supposed to pause the flow.
As we know, it**'**s very common, so it should probably not be in the outermost layer.

**Comment by sslater11** [comment]
@Glitchy-Tozier I've updated my script to include what you want.
https://github.com/sslater11/vim8_keyboard_most_common_letters/blob/main/keyboard_most_common_letter_pairs_english.py

There are 2 different tables it can output. Change this variable at the start of the file to switch between them.
```
# Toggle between a detailed or simple view of the similar letters table.
are_similar_letters_simple_view = False
```


I had to make it a more detailed output, since it didn't look right to me whilst writing the code.
Here's a sample of the detailed view
```
letters - frequency - percent | letters - frequency - percent | total - total percent
th      - 18570     - 5.09%   | ht      - 520       - 0.14%   | 19090 - 5.23%
re      - 7935      - 2.17%   | er      - 6963      - 1.91%   | 14898 - 4.08%
he      - 14368     - 3.94%   | eh      - 36        - 0.01%   | 14404 - 3.95%
an      - 10076     - 2.76%   | na      - 1004      - 0.28%   | 11080 - 3.04%
or      - 6490      - 1.78%   | ro      - 2338      - 0.64%   | 8828  - 2.42%
in      - 7847      - 2.15%   | ni      - 787       - 0.22%   | 8634  - 2.37%
of      - 5733      - 1.57%   | fo      - 2619      - 0.72%   | 8352  - 2.29%
to      - 6282      - 1.72%   | ot      - 1812      - 0.50%   | 8094  - 2.22%
it      - 4455      - 1.22%   | ti      - 2942      - 0.81%   | 7397  - 2.03%
```

And here's a sample of the simplified view.
```
letters |    percent   | total
th, ht  | 5.09%, 0.14% | 5.23%
re, er  | 2.17%, 1.91% | 4.08%
he, eh  | 3.94%, 0.01% | 3.95%
an, na  | 2.76%, 0.28% | 3.04%
or, ro  | 1.78%, 0.64% | 2.42%
in, ni  | 2.15%, 0.22% | 2.37%
of, fo  | 1.57%, 0.72% | 2.29%
to, ot  | 1.72%, 0.50% | 2.22%
it, ti  | 1.22%, 0.81% | 2.03%
```

I'm not sure as to how useful this will be, but we can at least see that "re, er" both have a high frequency, and can also see that with "th, ht" we don't need to really care about the "ht".

**Comment by Glitchy-Tozier** [comment]
Amazing work, thank you!!

One thing this can help us with is, as you recognized, improving the layout. For example, now that we know about `th` and `ht`, we can see that that your positioning-decisions are pretty good. You positioned `t` and `h` like this:
![8vimTH](https://user-images.githubusercontent.com/59611881/100514583-4ba5ef80-3176-11eb-8d0b-6b4962878c3f.jpg)
Which leads to a good flow on `th`, while not "wasting flow" on `ht`.

**Comment by sslater11** [comment]
Boobies haha.

**Comment by sslater11** [comment]
Well I finally made the layout and will be trying to learn it.
I also swapped the letters k and J around, and that seems to be all I can do based off my limited amount of bigrams.
Loving how well the letters align haha.
![8vim-my-layout](https://user-images.githubusercontent.com/43177940/100529269-b3435580-31dd-11eb-8800-c177b5e54657.png)

**Comment by Glitchy-Tozier** [comment]
I don't really feel qualified to rate this layout, I'm mostly iterested in German.
However, just looking at the `th`-placement, it _has_ to be better than the original Layout  xD

**Comment by sslater11** [comment]
I've been working on this script all morning.
https://github.com/sslater11/8vim_keyboard_layout_generator

You open it up, edit the first few variables and it'll generate the new keyboard layout(keyboard_actions.xml) for us :D.
I think it'll be handy for making new layouts for languages.

**Comment by Glitchy-Tozier** [comment]
Wow, nice!
If this message was aimed at me: I'll do it for the German language as soon as
1. I have double-checked the layout with the results of the language-research @flide wanted to do.
2. It's been approved by @flide and maybe a German-speaker that's not me.

(I _am_ pretty confident that it's _really good_ already but it's always good to have a second opinion.)

**Comment by sslater11** [comment]
That message was aimed at you and flide since I thought you'd both be interested in it :).

Just know that the Esperanto letter's movements are not changed and stay the same as the old layout, so if you use those movements just remember to remove the Esperanto bits from the file.

I'm only an English speaker and don't know about those fancy letters, but at least I've helped out a bit.

**Comment by Glitchy-Tozier** [comment]
Yeah, thanks for your contribution, even helping other languages!  :)

**Comment by Glitchy-Tozier** [comment]
Btw, do you count all the symbols? Like, did you include ? or ! or " or „ or ” or '

**Comment by sslater11** [comment]
No, as the original source only has the frequency of letters.
I did however do the basic maths of "they studied 250,000 words, divide that by the average sentence length to get a full stop's frequency", and then assumed that a comma was about as common lol. Doing that maths meant a comma and full stop should be on the 2nd movement space, which looks a bit counter intuitive to me, so although it may be more common than the letter z for example, I just didn't see how it could be more common than a p.

I think it was just easier to focus on the letters only, and think of punctuation separately, so I left those in the same place.

**Comment by Glitchy-Tozier** [comment]
>I think it was just easier to focus on the letters only, and think of punctuation separately, so I left those in the same place.

Understandably so. The reason why I asked is because (as far as I know) German supposedly uses more commas `,`. But since we're currently trending towards placing the special characters on the outer layers, it's not that important anyways. Just something interesting.

**Comment by Glitchy-Tozier** [comment]
Btw, I think you might want to try that test again with a bigger sample of real, normal texts.

The current results seem skewed.

I looked at the results of two universities and both find "th = `3,15%`
Another source found "th = `2,71%`"
You found "th = `5,09%`"

I'm not saying your script is faulty, but I think **analyzing whole books** is the way to go if you want to get results that better reflect language in use.
